/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.interfaz_grafica;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author felix-gabriel
 */

public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_enviar = new javax.swing.JButton();
        input_nombre = new javax.swing.JTextField();
        txt_titulo = new javax.swing.JLabel();
        input_apellido = new javax.swing.JTextField();
        input_edad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        input_perfil = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_enviar.setText("Enviar");
        bt_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_enviarActionPerformed(evt);
            }
        });

        input_nombre.setForeground(new java.awt.Color(153, 153, 153));
        input_nombre.setText("Ingrese su nombre");
        input_nombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_nombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_nombreFocusLost(evt);
            }
        });
        input_nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                input_nombreMouseClicked(evt);
            }
        });

        txt_titulo.setText("FORMULARIO DE REGISTRO");

        input_apellido.setForeground(new java.awt.Color(153, 153, 153));
        input_apellido.setText("Ingrese su apellido");
        input_apellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_apellidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_apellidoFocusLost(evt);
            }
        });
        input_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_apellidoActionPerformed(evt);
            }
        });

        input_edad.setForeground(new java.awt.Color(153, 153, 153));
        input_edad.setText("Ingrese su edad");
        input_edad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_edadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_edadFocusLost(evt);
            }
        });
        input_edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_edadActionPerformed(evt);
            }
        });

        input_perfil.setColumns(20);
        input_perfil.setForeground(new java.awt.Color(153, 153, 153));
        input_perfil.setRows(5);
        input_perfil.setText("Describa su perfil");
        input_perfil.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_perfilFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_perfilFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(input_perfil);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_titulo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_enviar)
                            .addComponent(input_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_titulo)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(input_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(input_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(input_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(bt_enviar))
                    .addComponent(jScrollPane1))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_apellidoActionPerformed

    private void input_edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_edadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_edadActionPerformed

    private void input_nombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_nombreMouseClicked
        
    }//GEN-LAST:event_input_nombreMouseClicked

    private void input_nombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_nombreFocusGained
        input_nombre.setForeground(Color.BLACK);
        input_nombre.setText("");
    }//GEN-LAST:event_input_nombreFocusGained

    private void input_nombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_nombreFocusLost
        if(input_nombre.getText().equals("Ingrese su nombre")){
            input_nombre.setForeground(Color.GRAY);
            input_nombre.setText("Ingrese su nombre");
        }
    }//GEN-LAST:event_input_nombreFocusLost

    private void input_apellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_apellidoFocusGained
        input_apellido.setForeground(Color.BLACK);
        input_apellido.setText("");
    }//GEN-LAST:event_input_apellidoFocusGained

    private void input_apellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_apellidoFocusLost
        if(input_apellido.getText().equals("Ingrese su apellido")){
            input_apellido.setForeground(Color.GRAY);
            input_apellido.setText("Ingrese su apellido");
        }
    }//GEN-LAST:event_input_apellidoFocusLost

    private void input_edadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_edadFocusGained
        input_edad.setForeground(Color.BLACK);
        input_edad.setText("");
    }//GEN-LAST:event_input_edadFocusGained

    private void input_edadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_edadFocusLost
        if(input_edad.getText().equals("Ingrese su edad")){    
            input_edad.setForeground(Color.GRAY);
            input_edad.setText("Ingrese su edad");
        }
    }//GEN-LAST:event_input_edadFocusLost

    private void input_perfilFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_perfilFocusGained
        input_perfil.setForeground(Color.BLACK);
        input_perfil.setText("");
    }//GEN-LAST:event_input_perfilFocusGained

    private void input_perfilFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_perfilFocusLost
        if(input_perfil.getText().equals("Describa su perfil")){    
            input_perfil.setForeground(Color.GRAY);
            input_perfil.setText("Describa su perfil");
        }
    }//GEN-LAST:event_input_perfilFocusLost

    private void bt_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_enviarActionPerformed
        String nombre = input_nombre.getText(), apellido = input_apellido.getText();
        String edad = input_edad.getText(), perfil = input_perfil.getText();
        
        if(nombre.equals("Ingrese su nombre")){
            input_nombre.setForeground(Color.RED);
        }else{
            if(apellido.equals("Ingrese su apellido")){
                input_apellido.setForeground(Color.RED);
            }else{
                if(edad.equals("Ingrese su edad")){
                    input_edad.setForeground(Color.RED);
                }else{
                    if(perfil.equals("Describa su perfil")){
                        input_perfil.setForeground(Color.RED);
                    }else{
                        JOptionPane.showMessageDialog(null, nombre.toUpperCase() + " " + apellido.toUpperCase() +"\nEdad: " + edad + "\nDescripcion:\n" + perfil);
                    }
                }
            }
        }
    }//GEN-LAST:event_bt_enviarActionPerformed
          
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatLightLaf.setup();
        UIManager.put( "Button.arc", 999 );
        UIManager.put( "Component.arc", 999 );
        UIManager.put( "ProgressBar.arc", 999 );
        UIManager.put( "TextComponent.arc", 999 );

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_enviar;
    private javax.swing.JTextField input_apellido;
    private javax.swing.JTextField input_edad;
    private javax.swing.JTextField input_nombre;
    private javax.swing.JTextArea input_perfil;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txt_titulo;
    // End of variables declaration//GEN-END:variables
}
